project:
  type: website
  output-dir: docs

website:
  title: "Mia B. Franco"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - Research.qmd

format:
  html:
    theme:
      light: pulse
      dark: slate
     
    css: styles.css
    toc: true
    page-layout: full

editor: visual

